/**
 * Default platform permissions seeded on startup.
 */
const DEFAULT_PERMISSIONS = [
  { name: 'View Users', slug: 'users:read', module: 'users', description: 'View user list and details' },
  { name: 'Create Users', slug: 'users:create', module: 'users', description: 'Create new users' },
  { name: 'Update Users', slug: 'users:update', module: 'users', description: 'Update user information' },
  { name: 'Delete Users', slug: 'users:delete', module: 'users', description: 'Deactivate users' },
  { name: 'View Roles', slug: 'roles:read', module: 'roles', description: 'View roles and permissions' },
  { name: 'Create Roles', slug: 'roles:create', module: 'roles', description: 'Create new roles' },
  { name: 'Update Roles', slug: 'roles:update', module: 'roles', description: 'Update roles' },
  { name: 'Delete Roles', slug: 'roles:delete', module: 'roles', description: 'Delete roles' },
  { name: 'Assign Roles', slug: 'roles:assign', module: 'roles', description: 'Assign roles to users' },
  { name: 'View Permissions', slug: 'permissions:read', module: 'permissions', description: 'View permissions' },
  { name: 'Create Permissions', slug: 'permissions:create', module: 'permissions', description: 'Create permissions' },
  { name: 'Update Permissions', slug: 'permissions:update', module: 'permissions', description: 'Update permissions' },
  { name: 'Delete Permissions', slug: 'permissions:delete', module: 'permissions', description: 'Delete permissions' },
  { name: 'Assign Permissions', slug: 'permissions:assign', module: 'permissions', description: 'Assign permissions to roles' },
  { name: 'View Specialties', slug: 'specialties:read', module: 'specialties', description: 'View medical specialties' },
  { name: 'Create Specialties', slug: 'specialties:create', module: 'specialties', description: 'Create medical specialties' },
  { name: 'Update Specialties', slug: 'specialties:update', module: 'specialties', description: 'Update medical specialties' },
  { name: 'Delete Specialties', slug: 'specialties:delete', module: 'specialties', description: 'Deactivate medical specialties' },
  { name: 'View Languages', slug: 'languages:read', module: 'languages', description: 'View languages' },
  { name: 'Create Languages', slug: 'languages:create', module: 'languages', description: 'Create languages' },
  { name: 'Update Languages', slug: 'languages:update', module: 'languages', description: 'Update languages' },
  { name: 'Delete Languages', slug: 'languages:delete', module: 'languages', description: 'Deactivate languages' },
  { name: 'View Doctors', slug: 'doctors:read', module: 'doctors', description: 'View doctor profiles' },
  { name: 'Create Doctors', slug: 'doctors:create', module: 'doctors', description: 'Create doctor profiles' },
  { name: 'Update Doctors', slug: 'doctors:update', module: 'doctors', description: 'Update doctor profiles' },
  { name: 'Delete Doctors', slug: 'doctors:delete', module: 'doctors', description: 'Deactivate doctors' },
  { name: 'Verify Doctors', slug: 'doctors:verify', module: 'doctors', description: 'Verify doctor credentials' },
  { name: 'Search Doctors', slug: 'doctors:search', module: 'doctors', description: 'Search verified doctors' },
  { name: 'View Doctor Availability', slug: 'doctors:availability:read', module: 'doctors', description: 'View doctor availability schedules' },
  { name: 'Manage Doctor Availability', slug: 'doctors:availability:update', module: 'doctors', description: 'Manage doctor availability schedules' },
  { name: 'View Clinics', slug: 'clinics:read', module: 'clinics', description: 'View clinics' },
  { name: 'Create Clinics', slug: 'clinics:create', module: 'clinics', description: 'Create clinics' },
  { name: 'Update Clinics', slug: 'clinics:update', module: 'clinics', description: 'Update clinics' },
  { name: 'Delete Clinics', slug: 'clinics:delete', module: 'clinics', description: 'Deactivate clinics' },
  { name: 'Assign Clinic Doctors', slug: 'clinics:assign-doctors', module: 'clinics', description: 'Assign doctors to clinics' },
  { name: 'View Patients', slug: 'patients:read', module: 'patients', description: 'View patient profiles' },
  { name: 'Create Patients', slug: 'patients:create', module: 'patients', description: 'Create patient profiles' },
  { name: 'Update Patients', slug: 'patients:update', module: 'patients', description: 'Update patient profiles' },
  { name: 'Delete Patients', slug: 'patients:delete', module: 'patients', description: 'Deactivate patients' },
  { name: 'View Family Members', slug: 'family-members:read', module: 'family-members', description: 'View family members' },
  { name: 'Create Family Members', slug: 'family-members:create', module: 'family-members', description: 'Create family members' },
  { name: 'Update Family Members', slug: 'family-members:update', module: 'family-members', description: 'Update family members' },
  { name: 'Delete Family Members', slug: 'family-members:delete', module: 'family-members', description: 'Remove family members' },
  { name: 'View Appointments', slug: 'appointments:read', module: 'appointments', description: 'View appointments' },
  { name: 'Book Appointments', slug: 'appointments:create', module: 'appointments', description: 'Book appointments' },
  { name: 'Update Appointments', slug: 'appointments:update', module: 'appointments', description: 'Update appointments' },
  { name: 'Cancel Appointments', slug: 'appointments:cancel', module: 'appointments', description: 'Cancel appointments' },
  { name: 'Manage Appointment Status', slug: 'appointments:status', module: 'appointments', description: 'Update appointment status' },
  { name: 'View Consultations', slug: 'consultations:read', module: 'consultations', description: 'View consultation records' },
  { name: 'Create Consultations', slug: 'consultations:create', module: 'consultations', description: 'Create consultation records' },
  { name: 'Update Consultations', slug: 'consultations:update', module: 'consultations', description: 'Update consultation records' },
  { name: 'Delete Consultations', slug: 'consultations:delete', module: 'consultations', description: 'Delete consultation records' },
  { name: 'View Prescriptions', slug: 'prescriptions:read', module: 'prescriptions', description: 'View prescriptions' },
  { name: 'Create Prescriptions', slug: 'prescriptions:create', module: 'prescriptions', description: 'Create prescriptions' },
  { name: 'Update Prescriptions', slug: 'prescriptions:update', module: 'prescriptions', description: 'Update prescriptions' },
  { name: 'Delete Prescriptions', slug: 'prescriptions:delete', module: 'prescriptions', description: 'Delete prescriptions' },
  { name: 'Download Prescription PDF', slug: 'prescriptions:pdf', module: 'prescriptions', description: 'Download prescription PDF' },
  { name: 'View Medical Records', slug: 'medical-records:read', module: 'medical-records', description: 'View medical records' },
  { name: 'Upload Medical Records', slug: 'medical-records:create', module: 'medical-records', description: 'Upload medical records' },
  { name: 'Update Medical Records', slug: 'medical-records:update', module: 'medical-records', description: 'Update medical records' },
  { name: 'Delete Medical Records', slug: 'medical-records:delete', module: 'medical-records', description: 'Delete medical records' },
  { name: 'Download Medical Records', slug: 'medical-records:download', module: 'medical-records', description: 'Download medical record files' },
  { name: 'View Reviews', slug: 'reviews:read', module: 'reviews', description: 'View reviews and ratings' },
  { name: 'Create Reviews', slug: 'reviews:create', module: 'reviews', description: 'Submit reviews' },
  { name: 'Update Reviews', slug: 'reviews:update', module: 'reviews', description: 'Edit reviews' },
  { name: 'Delete Reviews', slug: 'reviews:delete', module: 'reviews', description: 'Remove reviews' },
  { name: 'Moderate Reviews', slug: 'reviews:moderate', module: 'reviews', description: 'Moderate review visibility' },
  { name: 'View Notifications', slug: 'notifications:read', module: 'notifications', description: 'View notifications' },
  { name: 'Update Notification Preferences', slug: 'notifications:update', module: 'notifications', description: 'Manage notification preferences' },
  { name: 'Admin Notifications', slug: 'notifications:admin', module: 'notifications', description: 'View all platform notifications' },
  { name: 'View Payments', slug: 'payments:read', module: 'payments', description: 'View payment transactions' },
  { name: 'Create Payments', slug: 'payments:create', module: 'payments', description: 'Initiate payments' },
  { name: 'Refund Payments', slug: 'payments:refund', module: 'payments', description: 'Process payment refunds' },
  { name: 'Admin Payments', slug: 'payments:admin', module: 'payments', description: 'Manage all platform payments' },
  { name: 'View Dashboard', slug: 'dashboard:read', module: 'dashboard', description: 'View admin dashboard statistics' },
  { name: 'View Reports', slug: 'reports:read', module: 'reports', description: 'View platform reports' },
  { name: 'Export Reports', slug: 'reports:export', module: 'reports', description: 'Export reports to PDF or Excel' },
  { name: 'View Video Consultations', slug: 'video-consultations:read', module: 'video-consultations', description: 'View video consultation sessions' },
  { name: 'Join Video Consultations', slug: 'video-consultations:join', module: 'video-consultations', description: 'Join video consultation calls' },
  { name: 'Record Video Consultations', slug: 'video-consultations:record', module: 'video-consultations', description: 'Start and stop session recordings' },
  { name: 'View Medicines', slug: 'pharmacy:medicines:read', module: 'pharmacy', description: 'Browse medicine catalog' },
  { name: 'Manage Medicines', slug: 'pharmacy:medicines:write', module: 'pharmacy', description: 'Create and update medicines' },
  { name: 'View Inventory', slug: 'pharmacy:inventory:read', module: 'pharmacy', description: 'View pharmacy inventory' },
  { name: 'Manage Inventory', slug: 'pharmacy:inventory:write', module: 'pharmacy', description: 'Update pharmacy inventory' },
  { name: 'View Pharmacy Orders', slug: 'pharmacy:orders:read', module: 'pharmacy', description: 'View pharmacy orders' },
  { name: 'Place Pharmacy Orders', slug: 'pharmacy:orders:create', module: 'pharmacy', description: 'Place pharmacy orders' },
  { name: 'Fulfill Pharmacy Orders', slug: 'pharmacy:orders:fulfill', module: 'pharmacy', description: 'Update order fulfillment status' },
  { name: 'Upload Prescriptions', slug: 'pharmacy:prescription-uploads:create', module: 'pharmacy', description: 'Upload prescription images' },
  { name: 'Review Prescription Uploads', slug: 'pharmacy:prescription-uploads:review', module: 'pharmacy', description: 'Review uploaded prescriptions' },
  { name: 'View Labs', slug: 'lab:labs:read', module: 'lab', description: 'Browse lab listings' },
  { name: 'Manage Labs', slug: 'lab:labs:write', module: 'lab', description: 'Create and update labs' },
  { name: 'View Lab Tests', slug: 'lab:tests:read', module: 'lab', description: 'Browse lab tests' },
  { name: 'Manage Lab Tests', slug: 'lab:tests:write', module: 'lab', description: 'Create and update lab tests' },
  { name: 'View Lab Bookings', slug: 'lab:bookings:read', module: 'lab', description: 'View lab test bookings' },
  { name: 'Book Lab Tests', slug: 'lab:bookings:create', module: 'lab', description: 'Book lab tests and home collection' },
  { name: 'Fulfill Lab Bookings', slug: 'lab:bookings:fulfill', module: 'lab', description: 'Update lab booking status' },
  { name: 'View Lab Reports', slug: 'lab:reports:read', module: 'lab', description: 'View lab reports' },
  { name: 'Upload Lab Reports', slug: 'lab:reports:upload', module: 'lab', description: 'Upload lab test reports' },
  { name: 'View Chat Conversations', slug: 'chat:read', module: 'chat', description: 'View doctor-patient chat conversations' },
  { name: 'Send Chat Messages', slug: 'chat:send', module: 'chat', description: 'Send messages in doctor-patient chat' },
  { name: 'Upload Chat Attachments', slug: 'chat:attachments:upload', module: 'chat', description: 'Upload file attachments in chat' },
  { name: 'View Analytics', slug: 'analytics:read', module: 'analytics', description: 'View platform analytics and growth trends' },
  { name: 'View Audit Logs', slug: 'audit-logs:read', module: 'audit-logs', description: 'View system audit trail' },
  { name: 'View Settings', slug: 'settings:read', module: 'settings', description: 'View system settings' },
  { name: 'Manage Settings', slug: 'settings:write', module: 'settings', description: 'Update system settings' },
];

/**
 * Default system roles mapped to permission slugs.
 */
const DEFAULT_ROLES = [
  {
    name: 'Super Admin',
    slug: 'SUPER_ADMIN',
    description: 'Full platform access',
    isSystem: true,
    permissions: ['*'],
  },
  {
    name: 'Admin',
    slug: 'ADMIN',
    description: 'Platform administrator',
    isSystem: true,
    permissions: [
      'users:read', 'users:create', 'users:update', 'users:delete',
      'roles:read', 'roles:assign',
      'permissions:read',
      'specialties:read', 'specialties:create', 'specialties:update', 'specialties:delete',
      'languages:read', 'languages:create', 'languages:update', 'languages:delete',
      'doctors:read', 'doctors:create', 'doctors:update', 'doctors:delete', 'doctors:verify',
      'doctors:availability:read', 'doctors:availability:update',
      'clinics:read', 'clinics:create', 'clinics:update', 'clinics:delete', 'clinics:assign-doctors',
      'patients:read', 'patients:create', 'patients:update', 'patients:delete',
      'family-members:read', 'family-members:create', 'family-members:update', 'family-members:delete',
      'appointments:read', 'appointments:create', 'appointments:update', 'appointments:cancel', 'appointments:status',
      'consultations:read', 'consultations:create', 'consultations:update', 'consultations:delete',
      'prescriptions:read', 'prescriptions:create', 'prescriptions:update', 'prescriptions:delete', 'prescriptions:pdf',
      'medical-records:read', 'medical-records:create', 'medical-records:update', 'medical-records:delete', 'medical-records:download',
      'reviews:read', 'reviews:create', 'reviews:update', 'reviews:delete', 'reviews:moderate',
      'notifications:read', 'notifications:update', 'notifications:admin',
      'payments:read', 'payments:create', 'payments:refund', 'payments:admin',
      'dashboard:read',
      'reports:read', 'reports:export',
      'video-consultations:read', 'video-consultations:join', 'video-consultations:record',
      'pharmacy:medicines:read', 'pharmacy:medicines:write', 'pharmacy:inventory:read', 'pharmacy:inventory:write',
      'pharmacy:orders:read', 'pharmacy:orders:fulfill', 'pharmacy:prescription-uploads:review',
      'lab:labs:read', 'lab:labs:write', 'lab:tests:read', 'lab:tests:write',
      'lab:bookings:read', 'lab:bookings:fulfill', 'lab:reports:read', 'lab:reports:upload',
      'chat:read', 'chat:send', 'chat:attachments:upload',
      'analytics:read',
      'audit-logs:read',
      'settings:read', 'settings:write',
    ],
  },
  {
    name: 'Doctor',
    slug: 'DOCTOR',
    description: 'Healthcare provider',
    isSystem: true,
    permissions: ['users:read', 'specialties:read', 'languages:read', 'doctors:read', 'doctors:update', 'doctors:availability:read', 'doctors:availability:update', 'clinics:read', 'patients:read', 'family-members:read', 'appointments:read', 'appointments:status', 'appointments:update', 'appointments:cancel', 'consultations:read', 'consultations:create', 'consultations:update', 'prescriptions:read', 'prescriptions:create', 'prescriptions:update', 'prescriptions:pdf', 'medical-records:read', 'medical-records:create', 'medical-records:update', 'medical-records:download', 'reviews:read', 'notifications:read', 'notifications:update', 'payments:read', 'video-consultations:read', 'video-consultations:join', 'video-consultations:record', 'chat:read', 'chat:send', 'chat:attachments:upload'],
  },
  {
    name: 'Patient',
    slug: 'PATIENT',
    description: 'Healthcare consumer',
    isSystem: true,
    permissions: ['patients:read', 'patients:update', 'family-members:read', 'family-members:create', 'family-members:update', 'family-members:delete', 'doctors:search', 'specialties:read', 'languages:read', 'clinics:read', 'appointments:read', 'appointments:create', 'appointments:update', 'appointments:cancel', 'consultations:read', 'prescriptions:read', 'prescriptions:pdf', 'medical-records:read', 'medical-records:create', 'medical-records:update', 'medical-records:download', 'reviews:read', 'reviews:create', 'reviews:update', 'notifications:read', 'notifications:update', 'payments:read', 'payments:create', 'video-consultations:read', 'video-consultations:join', 'pharmacy:medicines:read', 'pharmacy:orders:read', 'pharmacy:orders:create', 'pharmacy:prescription-uploads:create', 'lab:labs:read', 'lab:tests:read', 'lab:bookings:read', 'lab:bookings:create', 'lab:reports:read', 'chat:read', 'chat:send', 'chat:attachments:upload'],
  },
  {
    name: 'Pharmacy',
    slug: 'PHARMACY',
    description: 'Pharmacy staff',
    isSystem: true,
    permissions: [
      'pharmacy:medicines:read', 'pharmacy:medicines:write',
      'pharmacy:inventory:read', 'pharmacy:inventory:write',
      'pharmacy:orders:read', 'pharmacy:orders:fulfill',
      'pharmacy:prescription-uploads:review',
      'patients:read', 'prescriptions:read',
      'notifications:read', 'notifications:update',
    ],
  },
  {
    name: 'Lab',
    slug: 'LAB',
    description: 'Diagnostic lab staff',
    isSystem: true,
    permissions: [
      'lab:labs:read', 'lab:labs:write',
      'lab:tests:read', 'lab:tests:write',
      'lab:bookings:read', 'lab:bookings:fulfill',
      'lab:reports:read', 'lab:reports:upload',
      'patients:read',
      'notifications:read', 'notifications:update',
    ],
  },
  {
    name: 'Clinic Manager',
    slug: 'CLINIC_MANAGER',
    description: 'Clinic operations manager',
    isSystem: true,
    permissions: ['users:read', 'clinics:read', 'clinics:update', 'clinics:assign-doctors', 'doctors:read'],
  },
];

module.exports = { DEFAULT_PERMISSIONS, DEFAULT_ROLES };
