const NotificationType = {
  APPOINTMENT_BOOKED: 'APPOINTMENT_BOOKED',
  APPOINTMENT_CONFIRMED: 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CANCELLED: 'APPOINTMENT_CANCELLED',
  APPOINTMENT_RESCHEDULED: 'APPOINTMENT_RESCHEDULED',
  APPOINTMENT_REMINDER: 'APPOINTMENT_REMINDER',
  PRESCRIPTION_READY: 'PRESCRIPTION_READY',
};

const NOTIFICATION_TYPE_VALUES = Object.values(NotificationType);

module.exports = { NotificationType, NOTIFICATION_TYPE_VALUES };
