const PaymentStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUND_PENDING: 'REFUND_PENDING',
  REFUNDED: 'REFUNDED',
  PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
};

const PAYMENT_STATUS_VALUES = Object.values(PaymentStatus);

const AppointmentPaymentStatus = {
  UNPAID: 'UNPAID',
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED',
  NOT_REQUIRED: 'NOT_REQUIRED',
};

const APPOINTMENT_PAYMENT_STATUS_VALUES = Object.values(AppointmentPaymentStatus);

module.exports = {
  PaymentStatus,
  PAYMENT_STATUS_VALUES,
  AppointmentPaymentStatus,
  APPOINTMENT_PAYMENT_STATUS_VALUES,
};
